# Generated by Django 6.0.3 on 2026-04-17 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.TextField(blank=True)),
                ('required_education', models.TextField(blank=True)),
                ('required_experience', models.CharField(blank=True, max_length=100)),
                ('required_languages', models.TextField(blank=True)),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('titre', models.CharField(blank=True, help_text='Titre du poste recherché', max_length=255, null=True)),
                ('hard_skills', models.TextField(blank=True, help_text='Compétences techniques (format JSON ou CSV)', null=True)),
                ('soft_skills', models.TextField(blank=True, help_text='Compétences humaines (format JSON ou CSV)', null=True)),
                ('experience_years', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('languages', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=255, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('debut', models.CharField(blank=True, help_text='Format: YYYY-MM', max_length=20, null=True)),
                ('fin', models.CharField(blank=True, help_text='Format: YYYY-MM (vide si en cours)', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.userprofile')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(blank=True, max_length=255, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('annee', models.CharField(blank=True, help_text="Année d'obtention", max_length=10, null=True)),
                ('domaine', models.CharField(blank=True, help_text="Domaine d'étude", max_length=255, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='api.userprofile')),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
    ]
