# Generated by Django 6.0.3 on 2026-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_joboffer_created_at_joboffer_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='source',
            field=models.CharField(blank=True, default='', help_text="Origine de l'offre : rekrute, emploima, marocannonces, manual…", max_length=50),
        ),
    ]
