# Generated by Django 6.0.3 on 2026-05-07 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_source_to_joboffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text="URL directe de l'offre sur le site source"),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Nom du site source : rekrute, emploima, marocannonces, manual…', max_length=50),
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('source', models.CharField(default='dataset', help_text='Mode utilisé : dataset, rekrute, emploima, marocannonces', max_length=50)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
