# Generated by Django 6.0.3 on 2026-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_searchhistory_and_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
    ]
